lavalink:
  server:
    bufferDurationMs: 400
    gc-warnings: true
    password: whatisyourproblem
    playerUpdateInterval: 5
    soundcloudSearchEnabled: true
    sources:
      bandcamp: true
      http: true
      local: false
      soundcloud: true
      twitch: true
      vimeo: true
      youtube: true
    youtubePlaylistLoadLimit: 3
    youtubeSearchEnabled: true
logging:
  file:
    max-history: 10
    max-size: 1GB
  level:
    lavalink: INFO
    root: INFO
  path: ./logs/
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
sentry:
  dsn: ""
  environment: ""
server:
  address: 0.0.0.0
  port: 1237
